const doWorkPromise = new Promise((resolve, reject) => {
    setTimeout(() => {
        reject('Error')
        // resolve([7, 4, 1])
    }, 2000);
})

doWorkPromise.then((result) => {
    console.log(result);
}).catch((error) => {
    console.log(error);
})